[package]
distribution = "2201.13.1"
org = "ballerinax"
name = "xlsx"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
# icon = "icon.png" # TODO: update icon.png
repository = "https://github.com/ballerina-platform/module-ballerina-xlsx"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
