[package]
distribution = "2201.13.1"
org = "ballerinax"
name = "xlsx"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["xlsx", "excel", "spreadsheet", "data"]
repository = "https://github.com/ballerina-platform/module-ballerina-xlsx"

[build-options]
observabilityIncluded = false

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "xlsx-native"
version = "0.1.0"
path = "../native/build/libs/xlsx-native-0.1.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "org.apache.poi"
artifactId = "poi"
version = "5.3.0"

[[platform.java21.dependency]]
groupId = "org.apache.poi"
artifactId = "poi-ooxml"
version = "5.3.0"

[[platform.java21.dependency]]
groupId = "org.apache.poi"
artifactId = "poi-ooxml-lite"
version = "5.3.0"

[[platform.java21.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-compress"
version = "1.26.0"

[[platform.java21.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-collections4"
version = "4.4"

[[platform.java21.dependency]]
groupId = "org.apache.xmlbeans"
artifactId = "xmlbeans"
version = "5.2.0"

[[platform.java21.dependency]]
groupId = "com.zaxxer"
artifactId = "SparseBitSet"
version = "1.3"

[[platform.java21.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "2.17.0"

[[platform.java21.dependency]]
groupId = "org.apache.logging.log4j"
artifactId = "log4j-api"
version = "2.21.1"

[[platform.java21.dependency]]
groupId = "org.apache.logging.log4j"
artifactId = "log4j-core"
version = "2.21.1"
